/* Generated by spimdisasm 1.11.1 */

glabel __start # 0
/* 000DC0 00400DC0 03E04025 */  move        $t0, $ra
/* 000DC4 00400DC4 04110001 */  bal         .L00400DCC
/* 000DC8 00400DC8 00000000 */   nop
.L00400DCC:


# _gp_disp: 0xFC0A524
.cpload $ra
/* 000DD8 00400DD8 0100F825 */  move        $ra, $t0
/* 000DDC 00400DDC 3C070000 */  lui         $a3, %got_hi(_environ)
/* 000DE0 00400DE0 00FC3821 */  addu        $a3, $a3, $gp
/* 000DE4 00400DE4 8CE7802C */  lw          $a3, %got_lo(_environ)($a3)
/* 000DE8 00400DE8 8FA40000 */  lw          $a0, 0x0($sp)
/* 000DEC 00400DEC 27A50004 */  addiu       $a1, $sp, 0x4
/* 000DF0 00400DF0 8CE70000 */  lw          $a3, 0x0($a3)
/* 000DF4 00400DF4 2401FFF0 */  addiu       $at, $zero, -0x10
/* 000DF8 00400DF8 03A1E824 */  and         $sp, $sp, $at
/* 000DFC 00400DFC 24A60004 */  addiu       $a2, $a1, 0x4
/* 000E00 00400E00 00041080 */  sll         $v0, $a0, 2
/* 000E04 00400E04 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 000E08 00400E08 14E00005 */  bnez        $a3, .L00400E20
/* 000E0C 00400E0C 00C23021 */   addu       $a2, $a2, $v0
/* 000E10 00400E10 3C010000 */  lui         $at, %got_hi(_environ)
/* 000E14 00400E14 003C0821 */  addu        $at, $at, $gp
/* 000E18 00400E18 8C21802C */  lw          $at, %got_lo(_environ)($at)
/* 000E1C 00400E1C AC260000 */  sw          $a2, 0x0($at)
.L00400E20:
/* 000E20 00400E20 3C010000 */  lui         $at, %got_hi(__Argc)
/* 000E24 00400E24 003C0821 */  addu        $at, $at, $gp
/* 000E28 00400E28 8C2180A4 */  lw          $at, %got_lo(__Argc)($at)
/* 000E2C 00400E2C 3C190000 */  lui         $t9, %call_hi(__istart)
/* 000E30 00400E30 033CC821 */  addu        $t9, $t9, $gp
/* 000E34 00400E34 AC240000 */  sw          $a0, 0x0($at)
/* 000E38 00400E38 3C010000 */  lui         $at, %got_hi(__Argv)
/* 000E3C 00400E3C 8F39809C */  lw          $t9, %call_lo(__istart)($t9)
/* 000E40 00400E40 003C0821 */  addu        $at, $at, $gp
/* 000E44 00400E44 8C2180A0 */  lw          $at, %got_lo(__Argv)($at)
/* 000E48 00400E48 AFBC0018 */  sw          $gp, 0x18($sp)
/* 000E4C 00400E4C AFA0001C */  sw          $zero, 0x1C($sp)
/* 000E50 00400E50 0000F025 */  move        $fp, $zero
/* 000E54 00400E54 0320F809 */  jalr        $t9
/* 000E58 00400E58 AC250000 */   sw         $a1, 0x0($at)
/* 000E5C 00400E5C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 000E60 00400E60 3C190000 */  lui         $t9, %call_hi(__readenv_sigfpe)
/* 000E64 00400E64 033CC821 */  addu        $t9, $t9, $gp
/* 000E68 00400E68 8F398038 */  lw          $t9, %call_lo(__readenv_sigfpe)($t9)
/* 000E6C 00400E6C 0320F809 */  jalr        $t9
/* 000E70 00400E70 00000000 */   nop
/* 000E74 00400E74 8FBC0018 */  lw          $gp, 0x18($sp)
/* 000E78 00400E78 3C190000 */  lui         $t9, %call_hi(main)
/* 000E7C 00400E7C 3C040000 */  lui         $a0, %got_hi(__Argc)
/* 000E80 00400E80 3C050000 */  lui         $a1, %got_hi(__Argv)
/* 000E84 00400E84 3C060000 */  lui         $a2, %got_hi(_environ)
/* 000E88 00400E88 033CC821 */  addu        $t9, $t9, $gp
/* 000E8C 00400E8C 8F39808C */  lw          $t9, %call_lo(main)($t9)
/* 000E90 00400E90 009C2021 */  addu        $a0, $a0, $gp
/* 000E94 00400E94 00BC2821 */  addu        $a1, $a1, $gp
/* 000E98 00400E98 00DC3021 */  addu        $a2, $a2, $gp
/* 000E9C 00400E9C 8C8480A4 */  lw          $a0, %got_lo(__Argc)($a0)
/* 000EA0 00400EA0 8CA580A0 */  lw          $a1, %got_lo(__Argv)($a1)
/* 000EA4 00400EA4 8CC6802C */  lw          $a2, %got_lo(_environ)($a2)
/* 000EA8 00400EA8 8C840000 */  lw          $a0, 0x0($a0)
/* 000EAC 00400EAC 8CA50000 */  lw          $a1, 0x0($a1)
/* 000EB0 00400EB0 0320F809 */  jalr        $t9
/* 000EB4 00400EB4 8CC60000 */   lw         $a2, 0x0($a2)
/* 000EB8 00400EB8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 000EBC 00400EBC 3C190000 */  lui         $t9, %call_hi(exit)
/* 000EC0 00400EC0 00402025 */  move        $a0, $v0
/* 000EC4 00400EC4 033CC821 */  addu        $t9, $t9, $gp
/* 000EC8 00400EC8 8F398034 */  lw          $t9, %call_lo(exit)($t9)
/* 000ECC 00400ECC 0320F809 */  jalr        $t9
/* 000ED0 00400ED0 00000000 */   nop
/* 000ED4 00400ED4 8FBC0018 */  lw          $gp, 0x18($sp)
/* 000ED8 00400ED8 0000000D */  break       0
