/* Generated by spimdisasm 1.11.1 */

glabel _mcount # 1
/* 000EDC 00400EDC 27BD0010 */  addiu       $sp, $sp, 0x10
/* 000EE0 00400EE0 03E00008 */  jr          $ra
/* 000EE4 00400EE4 0020F825 */   move       $ra, $at
/* 000EE8 00400EE8 00000000 */  nop
/* 000EEC 00400EEC 00000000 */  nop
/* 000EF0 00400EF0 00000000 */  nop
/* 000EF4 00400EF4 00000000 */  nop
/* 000EF8 00400EF8 00000000 */  nop
/* 000EFC 00400EFC 00000000 */  nop
