.section .rodata
glabel STR_1000302C
/* 00302C 1000302C */ .asciz "Usage:\n\tnrdc [options] [filename]\n\nOption:\n\t-h\thelp message\n\t-b\tbig endian\n\t-l\tlittle endian\n\t-t\ttitle patch\n\t-i\tinitial code patch\n\t-v\tversion patch\n\t-d\tregistration data dump\n\t-c\tCRC calculation\n\t-p\tregistration data patch\n\n"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel func_00401390 # 8


# _gp_disp: 0xFC09F60
.cpload $t9
/* 00139C 0040139C 8F99803C */  lw          $t9, %call16(printf)($gp)
/* 0013A0 004013A0 8F84801C */  lw          $a0, %got(STR_1000302C)($gp)
/* 0013A4 004013A4 27BDFFE0 */  addiu       $sp, $sp, -0x20
/* 0013A8 004013A8 AFBF001C */  sw          $ra, 0x1C($sp)
/* 0013AC 004013AC AFBC0018 */  sw          $gp, 0x18($sp)
/* 0013B0 004013B0 0320F809 */  jalr        $t9
/* 0013B4 004013B4 2484302C */   addiu      $a0, $a0, %lo(STR_1000302C)
/* 0013B8 004013B8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 0013BC 004013BC 00002025 */  move        $a0, $zero
/* 0013C0 004013C0 8F998034 */  lw          $t9, %call16(exit)($gp)
/* 0013C4 004013C4 0320F809 */  jalr        $t9
/* 0013C8 004013C8 00000000 */   nop
/* 0013CC 004013CC 8FBF001C */  lw          $ra, 0x1C($sp)
/* 0013D0 004013D0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 0013D4 004013D4 27BD0020 */  addiu       $sp, $sp, 0x20
/* 0013D8 004013D8 03E00008 */  jr          $ra
/* 0013DC 004013DC 00000000 */   nop
