/* Generated by spimdisasm 1.11.1 */

glabel func_00401A28 # 13


# _gp_disp: 0xFC098C8
.cpload $t9
/* 001A34 00401A34 8F8E801C */  lw          $t6, %got(D_100032F0)($gp)
/* 001A38 00401A38 27BDFFD8 */  addiu       $sp, $sp, -0x28
/* 001A3C 00401A3C 24010010 */  addiu       $at, $zero, 0x10
/* 001A40 00401A40 8DCE32F0 */  lw          $t6, %lo(D_100032F0)($t6)
/* 001A44 00401A44 AFBF001C */  sw          $ra, 0x1C($sp)
/* 001A48 00401A48 AFBC0018 */  sw          $gp, 0x18($sp)
/* 001A4C 00401A4C 31CF0030 */  andi        $t7, $t6, 0x30
/* 001A50 00401A50 15E10003 */  bne         $t7, $at, .L00401A60
/* 001A54 00401A54 AFA40028 */   sw         $a0, 0x28($sp)
/* 001A58 00401A58 10000024 */  b           .L00401AEC
/* 001A5C 00401A5C 00001025 */   move       $v0, $zero
.L00401A60:
/* 001A60 00401A60 8F98801C */  lw          $t8, %got(D_100032F0)($gp)
/* 001A64 00401A64 24010020 */  addiu       $at, $zero, 0x20
/* 001A68 00401A68 8F1832F0 */  lw          $t8, %lo(D_100032F0)($t8)
/* 001A6C 00401A6C 33190030 */  andi        $t9, $t8, 0x30
/* 001A70 00401A70 17210003 */  bne         $t9, $at, .L00401A80
/* 001A74 00401A74 00000000 */   nop
/* 001A78 00401A78 1000001C */  b           .L00401AEC
/* 001A7C 00401A7C 24020001 */   addiu      $v0, $zero, 0x1
.L00401A80:
/* 001A80 00401A80 8F998040 */  lw          $t9, %call16(strlen)($gp)
/* 001A84 00401A84 8FA40028 */  lw          $a0, 0x28($sp)
/* 001A88 00401A88 0320F809 */  jalr        $t9
/* 001A8C 00401A8C 00000000 */   nop
/* 001A90 00401A90 8FA80028 */  lw          $t0, 0x28($sp)
/* 001A94 00401A94 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001A98 00401A98 00484821 */  addu        $t1, $v0, $t0
/* 001A9C 00401A9C 912AFFFF */  lbu         $t2, -0x1($t1)
/* 001AA0 00401AA0 8F99805C */  lw          $t9, %call16(toupper)($gp)
/* 001AA4 00401AA4 AFAA0024 */  sw          $t2, 0x24($sp)
/* 001AA8 00401AA8 0320F809 */  jalr        $t9
/* 001AAC 00401AAC 01402025 */   move       $a0, $t2
/* 001AB0 00401AB0 24010042 */  addiu       $at, $zero, 0x42
/* 001AB4 00401AB4 14410003 */  bne         $v0, $at, .L00401AC4
/* 001AB8 00401AB8 8FBC0018 */   lw         $gp, 0x18($sp)
/* 001ABC 00401ABC 1000000B */  b           .L00401AEC
/* 001AC0 00401AC0 00001025 */   move       $v0, $zero
.L00401AC4:
/* 001AC4 00401AC4 8F99805C */  lw          $t9, %call16(toupper)($gp)
/* 001AC8 00401AC8 8FA40024 */  lw          $a0, 0x24($sp)
/* 001ACC 00401ACC 0320F809 */  jalr        $t9
/* 001AD0 00401AD0 00000000 */   nop
/* 001AD4 00401AD4 2401004C */  addiu       $at, $zero, 0x4C
/* 001AD8 00401AD8 14410003 */  bne         $v0, $at, .L00401AE8
/* 001ADC 00401ADC 8FBC0018 */   lw         $gp, 0x18($sp)
/* 001AE0 00401AE0 10000002 */  b           .L00401AEC
/* 001AE4 00401AE4 24020001 */   addiu      $v0, $zero, 0x1
.L00401AE8:
/* 001AE8 00401AE8 24020002 */  addiu       $v0, $zero, 0x2
.L00401AEC:
/* 001AEC 00401AEC 8FBF001C */  lw          $ra, 0x1C($sp)
/* 001AF0 00401AF0 27BD0028 */  addiu       $sp, $sp, 0x28
/* 001AF4 00401AF4 03E00008 */  jr          $ra
/* 001AF8 00401AF8 00000000 */   nop
