/* Generated by spimdisasm 1.11.1 */

glabel func_004014D8 # 10


# _gp_disp: 0xFC09E18
.cpload $t9
/* 0014E4 004014E4 28820030 */  slti        $v0, $a0, 0x30
/* 0014E8 004014E8 38420001 */  xori        $v0, $v0, 0x1
/* 0014EC 004014EC 10400002 */  beqz        $v0, .L004014F8
/* 0014F0 004014F0 00000000 */   nop
/* 0014F4 004014F4 28820038 */  slti        $v0, $a0, 0x38
.L004014F8:
/* 0014F8 004014F8 03E00008 */  jr          $ra
/* 0014FC 004014FC 00000000 */   nop
