.section .rodata
glabel STR_10003164
/* 003164 10003164 */ .asciz "NINTENDO 64 Master Data Utility  Version 1.02\n"
                      .balign 4

glabel STR_10003194
/* 003194 10003194 */ .asciz "Copyright(C) 1996 Nintendo Co.,LTD.\n\n"
                      .balign 4

glabel STR_100031BC
/* 0031BC 100031BC */ .asciz "rb+"
                      .balign 4

glabel STR_100031C0
/* 0031C0 100031C0 */ .asciz "rb"
                      .balign 4

glabel STR_100031C4
/* 0031C4 100031C4 */ .asciz "No input file"
                      .balign 4

glabel STR_100031D4
/* 0031D4 100031D4 */ .asciz "Unknown endianness"
                      .balign 4

glabel STR_100031E8
/* 0031E8 100031E8 */ .asciz "%s-endian\n\n"
                      .balign 4

glabel STR_100031F4
/* 0031F4 100031F4 */ .asciz "little"
                      .balign 4

glabel STR_100031FC
/* 0031FC 100031FC */ .asciz "big"
                      .balign 4


.section .text
/* Generated by spimdisasm 1.11.1 */

glabel main # 14


# _gp_disp: 0xFC097F4
.cpload $t9
/* 001B08 00401B08 27BDFFD0 */  addiu       $sp, $sp, -0x30
/* 001B0C 00401B0C 8F99803C */  lw          $t9, %call16(printf)($gp)
/* 001B10 00401B10 AFA40030 */  sw          $a0, 0x30($sp)
/* 001B14 00401B14 8F84801C */  lw          $a0, %got(STR_10003164)($gp)
/* 001B18 00401B18 AFBF001C */  sw          $ra, 0x1C($sp)
/* 001B1C 00401B1C 240E0001 */  addiu       $t6, $zero, 0x1
/* 001B20 00401B20 AFBC0018 */  sw          $gp, 0x18($sp)
/* 001B24 00401B24 AFA50034 */  sw          $a1, 0x34($sp)
/* 001B28 00401B28 AFB00014 */  sw          $s0, 0x14($sp)
/* 001B2C 00401B2C AFAE0028 */  sw          $t6, 0x28($sp)
/* 001B30 00401B30 0320F809 */  jalr        $t9
/* 001B34 00401B34 24843164 */   addiu      $a0, $a0, %lo(STR_10003164)
/* 001B38 00401B38 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001B3C 00401B3C 8F99803C */  lw          $t9, %call16(printf)($gp)
/* 001B40 00401B40 8F84801C */  lw          $a0, %got(STR_10003194)($gp)
/* 001B44 00401B44 0320F809 */  jalr        $t9
/* 001B48 00401B48 24843194 */   addiu      $a0, $a0, %lo(STR_10003194)
/* 001B4C 00401B4C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001B50 00401B50 8FA40030 */  lw          $a0, 0x30($sp)
/* 001B54 00401B54 8FA50034 */  lw          $a1, 0x34($sp)
/* 001B58 00401B58 8F998014 */  lw          $t9, %got(func_00401500)($gp)
/* 001B5C 00401B5C 2484FFFF */  addiu       $a0, $a0, -0x1
/* 001B60 00401B60 24A50004 */  addiu       $a1, $a1, 0x4
/* 001B64 00401B64 27391500 */  addiu       $t9, $t9, %lo(func_00401500)
/* 001B68 00401B68 0320F809 */  jalr        $t9
/* 001B6C 00401B6C 00000000 */   nop
/* 001B70 00401B70 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001B74 00401B74 8F8F801C */  lw          $t7, %got(D_100032F0)($gp)
/* 001B78 00401B78 8DEF32F0 */  lw          $t7, %lo(D_100032F0)($t7)
/* 001B7C 00401B7C 31F80004 */  andi        $t8, $t7, 0x4
/* 001B80 00401B80 1300000E */  beqz        $t8, .L00401BBC
/* 001B84 00401B84 00000000 */   nop
/* 001B88 00401B88 8FA80030 */  lw          $t0, 0x30($sp)
/* 001B8C 00401B8C 8FB90034 */  lw          $t9, 0x34($sp)
/* 001B90 00401B90 8F86801C */  lw          $a2, %got(B_100035C0)($gp)
/* 001B94 00401B94 00084880 */  sll         $t1, $t0, 2
/* 001B98 00401B98 03295021 */  addu        $t2, $t9, $t1
/* 001B9C 00401B9C 8F998084 */  lw          $t9, %call16(getcode)($gp)
/* 001BA0 00401BA0 8F84801C */  lw          $a0, %got(D_100032F0)($gp)
/* 001BA4 00401BA4 24C635C0 */  addiu       $a2, $a2, %lo(B_100035C0)
/* 001BA8 00401BA8 24C60004 */  addiu       $a2, $a2, 0x4
/* 001BAC 00401BAC 8D45FFFC */  lw          $a1, -0x4($t2)
/* 001BB0 00401BB0 0320F809 */  jalr        $t9
/* 001BB4 00401BB4 248432F0 */   addiu      $a0, $a0, %lo(D_100032F0)
/* 001BB8 00401BB8 8FBC0018 */  lw          $gp, 0x18($sp)
.L00401BBC:
/* 001BBC 00401BBC 8F8B801C */  lw          $t3, %got(D_100032F0)($gp)
/* 001BC0 00401BC0 8D6B32F0 */  lw          $t3, %lo(D_100032F0)($t3)
/* 001BC4 00401BC4 316C0100 */  andi        $t4, $t3, 0x100
/* 001BC8 00401BC8 1180000F */  beqz        $t4, .L00401C08
/* 001BCC 00401BCC 00000000 */   nop
/* 001BD0 00401BD0 8F8D801C */  lw          $t5, %got(B_100035C0)($gp)
/* 001BD4 00401BD4 8F998014 */  lw          $t9, %got(func_004017CC)($gp)
/* 001BD8 00401BD8 8F84801C */  lw          $a0, %got(B_100035D0)($gp)
/* 001BDC 00401BDC 25AD35C0 */  addiu       $t5, $t5, %lo(B_100035C0)
/* 001BE0 00401BE0 273917CC */  addiu       $t9, $t9, %lo(func_004017CC)
/* 001BE4 00401BE4 8DA50000 */  lw          $a1, 0x0($t5)
/* 001BE8 00401BE8 0320F809 */  jalr        $t9
/* 001BEC 00401BEC 248435D0 */   addiu      $a0, $a0, %lo(B_100035D0)
/* 001BF0 00401BF0 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001BF4 00401BF4 8F8E801C */  lw          $t6, %got(B_100035D0)($gp)
/* 001BF8 00401BF8 8F8F801C */  lw          $t7, %got(B_100035C0)($gp)
/* 001BFC 00401BFC 25CE35D0 */  addiu       $t6, $t6, %lo(B_100035D0)
/* 001C00 00401C00 25EF35C0 */  addiu       $t7, $t7, %lo(B_100035C0)
/* 001C04 00401C04 ADEE0000 */  sw          $t6, 0x0($t7)
.L00401C08:
/* 001C08 00401C08 8F98801C */  lw          $t8, %got(D_100032F0)($gp)
/* 001C0C 00401C0C 8F1832F0 */  lw          $t8, %lo(D_100032F0)($t8)
/* 001C10 00401C10 33080200 */  andi        $t0, $t8, 0x200
/* 001C14 00401C14 11000010 */  beqz        $t0, .L00401C58
/* 001C18 00401C18 00000000 */   nop
/* 001C1C 00401C1C 8F99801C */  lw          $t9, %got(B_100035C0)($gp)
/* 001C20 00401C20 8F84801C */  lw          $a0, %got(B_100035E8)($gp)
/* 001C24 00401C24 273935C0 */  addiu       $t9, $t9, %lo(B_100035C0)
/* 001C28 00401C28 8F250004 */  lw          $a1, 0x4($t9)
/* 001C2C 00401C2C 8F998014 */  lw          $t9, %got(func_004017CC)($gp)
/* 001C30 00401C30 248435E8 */  addiu       $a0, $a0, %lo(B_100035E8)
/* 001C34 00401C34 273917CC */  addiu       $t9, $t9, %lo(func_004017CC)
/* 001C38 00401C38 0320F809 */  jalr        $t9
/* 001C3C 00401C3C 00000000 */   nop
/* 001C40 00401C40 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001C44 00401C44 8F89801C */  lw          $t1, %got(B_100035E8)($gp)
/* 001C48 00401C48 8F8A801C */  lw          $t2, %got(B_100035C0)($gp)
/* 001C4C 00401C4C 252935E8 */  addiu       $t1, $t1, %lo(B_100035E8)
/* 001C50 00401C50 254A35C0 */  addiu       $t2, $t2, %lo(B_100035C0)
/* 001C54 00401C54 AD490004 */  sw          $t1, 0x4($t2)
.L00401C58:
/* 001C58 00401C58 8F8B801C */  lw          $t3, %got(D_100032F0)($gp)
/* 001C5C 00401C5C 8D6B32F0 */  lw          $t3, %lo(D_100032F0)($t3)
/* 001C60 00401C60 316C0400 */  andi        $t4, $t3, 0x400
/* 001C64 00401C64 1180000F */  beqz        $t4, .L00401CA4
/* 001C68 00401C68 00000000 */   nop
/* 001C6C 00401C6C 8F8D801C */  lw          $t5, %got(B_100035C0)($gp)
/* 001C70 00401C70 8F998014 */  lw          $t9, %got(func_004017CC)($gp)
/* 001C74 00401C74 8F84801C */  lw          $a0, %got(B_100035EE)($gp)
/* 001C78 00401C78 25AD35C0 */  addiu       $t5, $t5, %lo(B_100035C0)
/* 001C7C 00401C7C 273917CC */  addiu       $t9, $t9, %lo(func_004017CC)
/* 001C80 00401C80 8DA50008 */  lw          $a1, 0x8($t5)
/* 001C84 00401C84 0320F809 */  jalr        $t9
/* 001C88 00401C88 248435EE */   addiu      $a0, $a0, %lo(B_100035EE)
/* 001C8C 00401C8C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001C90 00401C90 8F8E801C */  lw          $t6, %got(B_100035EE)($gp)
/* 001C94 00401C94 8F8F801C */  lw          $t7, %got(B_100035C0)($gp)
/* 001C98 00401C98 25CE35EE */  addiu       $t6, $t6, %lo(B_100035EE)
/* 001C9C 00401C9C 25EF35C0 */  addiu       $t7, $t7, %lo(B_100035C0)
/* 001CA0 00401CA0 ADEE0008 */  sw          $t6, 0x8($t7)
.L00401CA4:
/* 001CA4 00401CA4 8F98801C */  lw          $t8, %got(D_100032F0)($gp)
/* 001CA8 00401CA8 8F1832F0 */  lw          $t8, %lo(D_100032F0)($t8)
/* 001CAC 00401CAC 33080004 */  andi        $t0, $t8, 0x4
/* 001CB0 00401CB0 11000004 */  beqz        $t0, .L00401CC4
/* 001CB4 00401CB4 00000000 */   nop
/* 001CB8 00401CB8 8F90801C */  lw          $s0, %got(STR_100031BC)($gp)
/* 001CBC 00401CBC 10000003 */  b           .L00401CCC
/* 001CC0 00401CC0 261031BC */   addiu      $s0, $s0, %lo(STR_100031BC)
.L00401CC4:
/* 001CC4 00401CC4 8F90801C */  lw          $s0, %got(STR_100031C0)($gp)
/* 001CC8 00401CC8 261031C0 */  addiu       $s0, $s0, %lo(STR_100031C0)
.L00401CCC:
/* 001CCC 00401CCC 8FA90030 */  lw          $t1, 0x30($sp)
/* 001CD0 00401CD0 8FB90034 */  lw          $t9, 0x34($sp)
/* 001CD4 00401CD4 02002825 */  move        $a1, $s0
/* 001CD8 00401CD8 00095080 */  sll         $t2, $t1, 2
/* 001CDC 00401CDC 032A5821 */  addu        $t3, $t9, $t2
/* 001CE0 00401CE0 8F998060 */  lw          $t9, %call16(fopen)($gp)
/* 001CE4 00401CE4 8D64FFFC */  lw          $a0, -0x4($t3)
/* 001CE8 00401CE8 0320F809 */  jalr        $t9
/* 001CEC 00401CEC 00000000 */   nop
/* 001CF0 00401CF0 AFA2002C */  sw          $v0, 0x2C($sp)
/* 001CF4 00401CF4 8FAC002C */  lw          $t4, 0x2C($sp)
/* 001CF8 00401CF8 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001CFC 00401CFC 15800006 */  bnez        $t4, .L00401D18
/* 001D00 00401D00 00000000 */   nop
/* 001D04 00401D04 8F998088 */  lw          $t9, %call16(error)($gp)
/* 001D08 00401D08 8F84801C */  lw          $a0, %got(STR_100031C4)($gp)
/* 001D0C 00401D0C 0320F809 */  jalr        $t9
/* 001D10 00401D10 248431C4 */   addiu      $a0, $a0, %lo(STR_100031C4)
/* 001D14 00401D14 8FBC0018 */  lw          $gp, 0x18($sp)
.L00401D18:
/* 001D18 00401D18 8FAE0030 */  lw          $t6, 0x30($sp)
/* 001D1C 00401D1C 8FAD0034 */  lw          $t5, 0x34($sp)
/* 001D20 00401D20 8F998014 */  lw          $t9, %got(func_00401A28)($gp)
/* 001D24 00401D24 000E7880 */  sll         $t7, $t6, 2
/* 001D28 00401D28 01AFC021 */  addu        $t8, $t5, $t7
/* 001D2C 00401D2C 27391A28 */  addiu       $t9, $t9, %lo(func_00401A28)
/* 001D30 00401D30 0320F809 */  jalr        $t9
/* 001D34 00401D34 8F04FFFC */   lw         $a0, -0x4($t8)
/* 001D38 00401D38 AFA20028 */  sw          $v0, 0x28($sp)
/* 001D3C 00401D3C 8FA80028 */  lw          $t0, 0x28($sp)
/* 001D40 00401D40 24010002 */  addiu       $at, $zero, 0x2
/* 001D44 00401D44 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001D48 00401D48 15010006 */  bne         $t0, $at, .L00401D64
/* 001D4C 00401D4C 00000000 */   nop
/* 001D50 00401D50 8F998088 */  lw          $t9, %call16(error)($gp)
/* 001D54 00401D54 8F84801C */  lw          $a0, %got(STR_100031D4)($gp)
/* 001D58 00401D58 0320F809 */  jalr        $t9
/* 001D5C 00401D5C 248431D4 */   addiu      $a0, $a0, %lo(STR_100031D4)
/* 001D60 00401D60 8FBC0018 */  lw          $gp, 0x18($sp)
.L00401D64:
/* 001D64 00401D64 8FA90028 */  lw          $t1, 0x28($sp)
/* 001D68 00401D68 24010001 */  addiu       $at, $zero, 0x1
/* 001D6C 00401D6C 15210004 */  bne         $t1, $at, .L00401D80
/* 001D70 00401D70 00000000 */   nop
/* 001D74 00401D74 8F90801C */  lw          $s0, %got(STR_100031F4)($gp)
/* 001D78 00401D78 10000003 */  b           .L00401D88
/* 001D7C 00401D7C 261031F4 */   addiu      $s0, $s0, %lo(STR_100031F4)
.L00401D80:
/* 001D80 00401D80 8F90801C */  lw          $s0, %got(STR_100031FC)($gp)
/* 001D84 00401D84 261031FC */  addiu       $s0, $s0, %lo(STR_100031FC)
.L00401D88:
/* 001D88 00401D88 8F99803C */  lw          $t9, %call16(printf)($gp)
/* 001D8C 00401D8C 8F84801C */  lw          $a0, %got(STR_100031E8)($gp)
/* 001D90 00401D90 02002825 */  move        $a1, $s0
/* 001D94 00401D94 0320F809 */  jalr        $t9
/* 001D98 00401D98 248431E8 */   addiu      $a0, $a0, %lo(STR_100031E8)
/* 001D9C 00401D9C 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001DA0 00401DA0 8F99801C */  lw          $t9, %got(D_100032F0)($gp)
/* 001DA4 00401DA4 8F3932F0 */  lw          $t9, %lo(D_100032F0)($t9)
/* 001DA8 00401DA8 332A0004 */  andi        $t2, $t9, 0x4
/* 001DAC 00401DAC 11400009 */  beqz        $t2, .L00401DD4
/* 001DB0 00401DB0 00000000 */   nop
/* 001DB4 00401DB4 03202025 */  move        $a0, $t9
/* 001DB8 00401DB8 8F998094 */  lw          $t9, %call16(nrdc_patch)($gp)
/* 001DBC 00401DBC 8F87801C */  lw          $a3, %got(B_100035C0)($gp)
/* 001DC0 00401DC0 8FA50028 */  lw          $a1, 0x28($sp)
/* 001DC4 00401DC4 8FA6002C */  lw          $a2, 0x2C($sp)
/* 001DC8 00401DC8 0320F809 */  jalr        $t9
/* 001DCC 00401DCC 24E735C0 */   addiu      $a3, $a3, %lo(B_100035C0)
/* 001DD0 00401DD0 8FBC0018 */  lw          $gp, 0x18($sp)
.L00401DD4:
/* 001DD4 00401DD4 8F8B801C */  lw          $t3, %got(D_100032F0)($gp)
/* 001DD8 00401DD8 8D6B32F0 */  lw          $t3, %lo(D_100032F0)($t3)
/* 001DDC 00401DDC 316C0002 */  andi        $t4, $t3, 0x2
/* 001DE0 00401DE0 11800007 */  beqz        $t4, .L00401E00
/* 001DE4 00401DE4 00000000 */   nop
/* 001DE8 00401DE8 8F998090 */  lw          $t9, %call16(nrdc_dump)($gp)
/* 001DEC 00401DEC 8FA40028 */  lw          $a0, 0x28($sp)
/* 001DF0 00401DF0 8FA5002C */  lw          $a1, 0x2C($sp)
/* 001DF4 00401DF4 0320F809 */  jalr        $t9
/* 001DF8 00401DF8 00000000 */   nop
/* 001DFC 00401DFC 8FBC0018 */  lw          $gp, 0x18($sp)
.L00401E00:
/* 001E00 00401E00 8F8E801C */  lw          $t6, %got(D_100032F0)($gp)
/* 001E04 00401E04 8DCE32F0 */  lw          $t6, %lo(D_100032F0)($t6)
/* 001E08 00401E08 31CD0001 */  andi        $t5, $t6, 0x1
/* 001E0C 00401E0C 11A0000C */  beqz        $t5, .L00401E40
/* 001E10 00401E10 00000000 */   nop
/* 001E14 00401E14 8F998064 */  lw          $t9, %call16(rewind)($gp)
/* 001E18 00401E18 8FA4002C */  lw          $a0, 0x2C($sp)
/* 001E1C 00401E1C 0320F809 */  jalr        $t9
/* 001E20 00401E20 00000000 */   nop
/* 001E24 00401E24 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001E28 00401E28 8FA40028 */  lw          $a0, 0x28($sp)
/* 001E2C 00401E2C 8FA5002C */  lw          $a1, 0x2C($sp)
/* 001E30 00401E30 8F998080 */  lw          $t9, %call16(nrdc_crc)($gp)
/* 001E34 00401E34 0320F809 */  jalr        $t9
/* 001E38 00401E38 00000000 */   nop
/* 001E3C 00401E3C 8FBC0018 */  lw          $gp, 0x18($sp)
.L00401E40:
/* 001E40 00401E40 8F998068 */  lw          $t9, %call16(fclose)($gp)
/* 001E44 00401E44 8FA4002C */  lw          $a0, 0x2C($sp)
/* 001E48 00401E48 0320F809 */  jalr        $t9
/* 001E4C 00401E4C 00000000 */   nop
/* 001E50 00401E50 8FBF001C */  lw          $ra, 0x1C($sp)
/* 001E54 00401E54 8FBC0018 */  lw          $gp, 0x18($sp)
/* 001E58 00401E58 8FB00014 */  lw          $s0, 0x14($sp)
/* 001E5C 00401E5C 27BD0030 */  addiu       $sp, $sp, 0x30
/* 001E60 00401E60 03E00008 */  jr          $ra
/* 001E64 00401E64 00001025 */   move       $v0, $zero
/* 001E68 00401E68 00000000 */  nop
/* 001E6C 00401E6C 00000000 */  nop
