.include "macro.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches

.section .data

.balign 16

/* Generated by spimdisasm 1.11.1 */

glabel D_100032E0
/* 0032E0 100032E0 */ .word 0x00000000
/* 0032E4 100032E4 */ .word 0x00000000
/* 0032E8 100032E8 */ .word 0x00000000
/* 0032EC 100032EC */ .word 0x00000000

glabel D_100032F0
/* 0032F0 100032F0 */ .word 0x00000000
/* 0032F4 100032F4 */ .word 0x00000000
/* 0032F8 100032F8 */ .word 0x00000000
/* 0032FC 100032FC */ .word 0x00000000
