.include "macro.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches

.section .bss

.balign 16

/* Generated by spimdisasm 1.11.1 */

glabel B_100033A0
/* 003398 100033A0 */ .space 0x08

glabel B_100033A8
/* 0033A0 100033A8 */ .space 0x208

glabel B_100035B0
/* 0035A8 100035B0 */ .space 0x06

glabel B_100035B6
/* 0035AE 100035B6 */ .space 0x0A

glabel B_100035C0
/* 0035B8 100035C0 */ .space 0x10

glabel B_100035D0
/* 0035C8 100035D0 */ .space 0x18

glabel B_100035E8
/* 0035E0 100035E8 */ .space 0x06

glabel B_100035EE
/* 0035E6 100035EE */ .space 0x12

glabel B_10003600
/* 0035F8 10003600 */ .space 0x20

glabel B_10003620
/* 003618 10003620 */ .space 0x20

glabel __Argv
/* 003638 10003640 */ .space 0x04

glabel __rld_obj_head
/* 00363C 10003644 */ .space 0x04

glabel __Argc
/* 003640 10003648 */ .space 0x04
