.include "macro.inc"

# assembler directives
.set noat      # allow manual use of $at
.set noreorder # don't insert nops after branches

.section .rodata

.balign 16

/* Generated by spimdisasm 1.11.1 */

glabel STR_10003000
/* 003000 10003000 */ .asciz "CRC = 0x%04x\n"
                      .balign 4

glabel STR_10003010
/* 003010 10003010 */ .asciz ".SRB"
                      .balign 4
/* 003018 10003018 */ .asciz ""
                      .balign 4
/* 00301C 1000301C */ .asciz ""
                      .balign 4

glabel RO_10003020
/* 003020 10003020 07457272 */ .word 0x07457272
/* 003024 10003024 6F723A20 */ .word 0x6F723A20
/* 003028 10003028 25730A00 */ .word 0x25730A00

glabel STR_1000302C
/* 00302C 1000302C */ .asciz "Usage:\n\tnrdc [options] [filename]\n\nOption:\n\t-h\thelp message\n\t-b\tbig endian\n\t-l\tlittle endian\n\t-t\ttitle patch\n\t-i\tinitial code patch\n\t-v\tversion patch\n\t-d\tregistration data dump\n\t-c\tCRC calculation\n\t-p\tregistration data patch\n\n"
                      .balign 4

glabel RO_10003110
/* 003110 10003110 00000000 */ .word 0x00000000

glabel STR_10003114
/* 003114 10003114 */ .asciz "-h"
                      .balign 4

glabel STR_10003118
/* 003118 10003118 */ .asciz "-?"
                      .balign 4

glabel STR_1000311C
/* 00311C 1000311C */ .asciz "-c"
                      .balign 4

glabel STR_10003120
/* 003120 10003120 */ .asciz "-d"
                      .balign 4

glabel STR_10003124
/* 003124 10003124 */ .asciz "-p"
                      .balign 4

glabel STR_10003128
/* 003128 10003128 */ .asciz "-b"
                      .balign 4

glabel STR_1000312C
/* 00312C 1000312C */ .asciz "-l"
                      .balign 4

glabel STR_10003130
/* 003130 10003130 */ .asciz "-t"
                      .balign 4

glabel STR_10003134
/* 003134 10003134 */ .asciz "-i"
                      .balign 4

glabel STR_10003138
/* 003138 10003138 */ .asciz "-v"
                      .balign 4

glabel RO_1000313C
/* 00313C 1000313C 07576172 */ .word 0x07576172
/* 003140 10003140 6E696E67 */ .word 0x6E696E67
/* 003144 10003144 3A202225 */ .word 0x3A202225
/* 003148 10003148 7322206F */ .word 0x7322206F
/* 00314C 1000314C 7074696F */ .word 0x7074696F
/* 003150 10003150 6E206973 */ .word 0x6E206973
/* 003154 10003154 20756E72 */ .word 0x20756E72
/* 003158 10003158 65636F67 */ .word 0x65636F67
/* 00315C 1000315C 6E697A65 */ .word 0x6E697A65
/* 003160 10003160 642E0A00 */ .word 0x642E0A00

glabel STR_10003164
/* 003164 10003164 */ .asciz "NINTENDO 64 Master Data Utility  Version 1.02\n"
                      .balign 4

glabel STR_10003194
/* 003194 10003194 */ .asciz "Copyright(C) 1996 Nintendo Co.,LTD.\n\n"
                      .balign 4

glabel STR_100031BC
/* 0031BC 100031BC */ .asciz "rb+"
                      .balign 4

glabel STR_100031C0
/* 0031C0 100031C0 */ .asciz "rb"
                      .balign 4

glabel STR_100031C4
/* 0031C4 100031C4 */ .asciz "No input file"
                      .balign 4

glabel STR_100031D4
/* 0031D4 100031D4 */ .asciz "Unknown endianness"
                      .balign 4

glabel STR_100031E8
/* 0031E8 100031E8 */ .asciz "%s-endian\n\n"
                      .balign 4

glabel STR_100031F4
/* 0031F4 100031F4 */ .asciz "little"
                      .balign 4

glabel STR_100031FC
/* 0031FC 100031FC */ .asciz "big"
                      .balign 4

glabel STR_10003200
/* 003200 10003200 */ .asciz "ROM ADDR"
                      .balign 4

glabel STR_1000320C
/* 00320C 1000320C */ .asciz " +%x"
                      .balign 4

glabel STR_10003214
/* 003214 10003214 */ .asciz "\n%08lx"
                      .balign 4

glabel STR_1000321C
/* 00321C 1000321C */ .asciz " %02x"
                      .balign 4

glabel STR_10003224
/* 003224 10003224 */ .asciz "\n%08lx"
                      .balign 4

glabel STR_1000322C
/* 00322C 1000322C */ .asciz " %02x"
                      .balign 4

glabel STR_10003234
/* 003234 10003234 */ .asciz "\n\nGame Title:   %.*s\nInitial Code: %.4s\nVersion:      %x\n\n"
                      .balign 4

glabel RO_10003270
/* 003270 10003270 07576172 */ .word 0x07576172
/* 003274 10003274 6E696E67 */ .word 0x6E696E67
/* 003278 10003278 3A20496E */ .word 0x3A20496E
/* 00327C 1000327C 76616C69 */ .word 0x76616C69
/* 003280 10003280 64206761 */ .word 0x64206761
/* 003284 10003284 6D65206E */ .word 0x6D65206E
/* 003288 10003288 616D650A */ .word 0x616D650A
/* 00328C 1000328C 00000000 */ .word 0x00000000

glabel RO_10003290
/* 003290 10003290 07576172 */ .word 0x07576172
/* 003294 10003294 6E696E67 */ .word 0x6E696E67
/* 003298 10003298 3A20496E */ .word 0x3A20496E
/* 00329C 1000329C 76616C69 */ .word 0x76616C69
/* 0032A0 100032A0 6420696E */ .word 0x6420696E
/* 0032A4 100032A4 7469616C */ .word 0x7469616C
/* 0032A8 100032A8 20636F64 */ .word 0x20636F64
/* 0032AC 100032AC 650A0000 */ .word 0x650A0000

glabel RO_100032B0
/* 0032B0 100032B0 07576172 */ .word 0x07576172
/* 0032B4 100032B4 6E696E67 */ .word 0x6E696E67
/* 0032B8 100032B8 3A20496E */ .word 0x3A20496E
/* 0032BC 100032BC 76616C69 */ .word 0x76616C69
/* 0032C0 100032C0 64207665 */ .word 0x64207665
/* 0032C4 100032C4 7273696F */ .word 0x7273696F
/* 0032C8 100032C8 6E206E75 */ .word 0x6E206E75
/* 0032CC 100032CC 6D626572 */ .word 0x6D626572
/* 0032D0 100032D0 0A000000 */ .word 0x0A000000
/* 0032D4 100032D4 00000000 */ .word 0x00000000
/* 0032D8 100032D8 00000000 */ .word 0x00000000
/* 0032DC 100032DC 00000000 */ .word 0x00000000
